# Versão do docker-compose
version: "3.9"

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /home/mrafaelbatista/databases/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="<YOUR ROOT'S PASSWORD>"
      - MYSQL_PASSWORD="<YOUR PASSWORD>"
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./containers/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=#a1b2c3d4
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
